class BackgroundUtil {
  static var mapBackground = {
    '01d': 'assets/day_clearsky.9.png',
    '01n': 'assets/night_clearsky.9.png',
    '02d': 'assets/day_partlycloudy.9.png',
    '02n': 'assets/night_partlycloudy.9.png',
    '03d': 'assets/day_cloudy.9.png',
    '03n': 'assets/night_cloudy.9.png',
    '04d': 'assets/day_cloudy.9.png',
    '04n': 'assets/night_cloudy.9.png',
    '09d': 'assets/day_rain.9.png',
    '09n': 'assets/night_rain.9.png',
    '10d': 'assets/day_rain.9.png',
    '10n': 'assets/night_rain.9.png',
    '11d': 'assets/day_rain.9.png',
    '11n': 'assets/night_rain.9.png',
    '13d': 'assets/day_snow.9.png',
    '13n': 'assets/night_snow.9.png',
    '50d': 'assets/day_fog.9.png',
    '50n': 'assets/day_fog.9.png'
  };
  static var mapBackgroundChild = {
    '01d': 'assets/day_clearsky_2x4.png',
    '01n': 'assets/night_clearsky_2x4.png',
    '02d': 'assets/day_partlycloudy_2x4.png',
    '02n': 'assets/night_partlycloudy_2x4.png',
    '03d': 'assets/day_cloudy_2x4.png',
    '03n': 'assets/night_cloudy_2x4.png',
    '04d': 'assets/day_cloudy_2x4.png',
    '04n': 'assets/night_cloudy_2x4.png',
    '09d': 'assets/day_rain_2x4.png',
    '09n': 'assets/night_rain_2x4.png',
    '10d': 'assets/day_rain_2x4.png',
    '10n': 'assets/night_rain_2x4.png',
    '11d': 'assets/day_rain_2x4.png',
    '11n': 'assets/night_rain_2x4.png',
    '13d': 'assets/day_snow_2x4.png',
    '13n': 'assets/night_snow_2x4.png',
    '50d': 'assets/day_fog_2x4.png',
    '50n': 'assets/day_fog_2x4.png'
  };
  static var mapNameIcon = {
    '01d': 'sunny',
    '01n': 'moon',
    '02d': 'sunny_cloud',
    '02n': 'moon_cloud',
    '03d': 'sunny_cloud2',
    '03n': 'moon_cloud2',
    '04d': 'sunny_cloud2',
    '04n': 'moon_cloud2',
    '09d': 'sunny_rain',
    '09n': 'moon_rain',
    '10d': 'sunny_rain',
    '10n': 'moon_rain',
    '11d': 'sunny_rain',
    '11n': 'moon_rain',
    '13d': 'sunny_snow',
    '13n': 'moon_snow',
    '50d': 'sunny_frog',
    '50n': 'moon_frog'
  };
}
